/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:29 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit.h>

@protocol TUICandidateViewStyle;
@class UIImageView;

@interface TUICandidateBaseCell : UICollectionViewCell {

	id<TUICandidateViewStyle> _style;
	UIImageView* _backgroundImageView;

}

@property (nonatomic,retain) UIImageView * backgroundImageView;              //@synthesize backgroundImageView=_backgroundImageView - In the implementation block
@property (nonatomic,retain) id<TUICandidateViewStyle> style;                //@synthesize style=_style - In the implementation block
-(id<TUICandidateViewStyle>)style;
-(void)setSelected:(BOOL)arg1 ;
-(void)setStyle:(id<TUICandidateViewStyle>)arg1 ;
-(id)cellBackgroundColor;
-(void)setHighlighted:(BOOL)arg1 ;
-(UIImageView *)backgroundImageView;
-(id)cellBackgroundImage;
-(void)updateColors;
-(void)updateBackground:(id)arg1 color:(id)arg2 ;
-(void)setBackgroundImageView:(UIImageView *)arg1 ;
@end

