/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:29 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit.h>

@class NSString, UIFont, UIColor;

@interface TUICandidateLabel : UIView {

	BOOL _adjustsFontSizeToFitWidth;
	NSString* _text;
	UIFont* _font;
	double _minimumScaleFactor;
	UIColor* _textColor;
	long long _layoutOrientation;
	long long _lineBreakMode;

}

@property (nonatomic,copy) NSString * text;                               //@synthesize text=_text - In the implementation block
@property (nonatomic,retain) UIFont * font;                               //@synthesize font=_font - In the implementation block
@property (assign,nonatomic) double minimumScaleFactor;                   //@synthesize minimumScaleFactor=_minimumScaleFactor - In the implementation block
@property (assign,nonatomic) BOOL adjustsFontSizeToFitWidth;              //@synthesize adjustsFontSizeToFitWidth=_adjustsFontSizeToFitWidth - In the implementation block
@property (nonatomic,retain) UIColor * textColor;                         //@synthesize textColor=_textColor - In the implementation block
@property (assign,nonatomic) long long layoutOrientation;                 //@synthesize layoutOrientation=_layoutOrientation - In the implementation block
@property (assign,nonatomic) long long lineBreakMode;                     //@synthesize lineBreakMode=_lineBreakMode - In the implementation block
+(double)lineWidthForText:(id)arg1 font:(id)arg2 layoutOrientation:(long long)arg3 ;
-(void)setLayoutOrientation:(long long)arg1 ;
-(id)accessibilityLabel;
-(void)setLineBreakMode:(long long)arg1 ;
-(unsigned long long)accessibilityTraits;
-(void)drawRect:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setMinimumScaleFactor:(double)arg1 ;
-(void)setTextColor:(UIColor *)arg1 ;
-(void)setText:(NSString *)arg1 ;
-(void)setAdjustsFontSizeToFitWidth:(BOOL)arg1 ;
-(long long)lineBreakMode;
-(NSString *)text;
-(BOOL)adjustsFontSizeToFitWidth;
-(double)minimumScaleFactor;
-(UIColor *)textColor;
-(void)commonInit;
-(UIFont *)font;
-(long long)layoutOrientation;
-(id)initWithCoder:(id)arg1 ;
-(void)setFont:(UIFont *)arg1 ;
-(unsigned)lineTruncationType;
-(id)createLineFromAttributedText:(id)arg1 ;
@end

