/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:29 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit.h>

@protocol TUIPredictionViewDelegate;
@class TIAutocorrectionList, UIView, NSLocale, UIKBRenderConfig, UIColor, TUIPredictionViewStackView, UILongPressGestureRecognizer, NSArray, NSString;

@interface TUIPredictionView : UIView <UIGestureRecognizerDelegate> {

	BOOL _drawsBackdropView;
	BOOL _disablesHighlight;
	BOOL _useContinuousCornerInHighlight;
	BOOL _shouldAnimateCells;
	id<TUIPredictionViewDelegate> _delegate;
	long long _selectedIndex;
	TIAutocorrectionList* _autocorrectionList;
	UIView* _backdropView;
	unsigned long long _minimumNumberOfCells;
	unsigned long long _maximumEmojiCells;
	NSLocale* _currentLocale;
	UIKBRenderConfig* _renderConfig;
	UIColor* _separatorColor;
	double _separatorMargin;
	UIColor* _highlightColor;
	double _highlightMargin;
	double _highlightCornerRadius;
	TUIPredictionViewStackView* _cellStackView;
	UILongPressGestureRecognizer* _tapGestureRecognizer;

}

@property (nonatomic,retain) UIView * backdropView;                                            //@synthesize backdropView=_backdropView - In the implementation block
@property (nonatomic,retain) TUIPredictionViewStackView * cellStackView;                       //@synthesize cellStackView=_cellStackView - In the implementation block
@property (nonatomic,retain) UILongPressGestureRecognizer * tapGestureRecognizer;              //@synthesize tapGestureRecognizer=_tapGestureRecognizer - In the implementation block
@property (assign,nonatomic) id<TUIPredictionViewDelegate> delegate;                           //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) long long selectedIndex;                                          //@synthesize selectedIndex=_selectedIndex - In the implementation block
@property (nonatomic,retain) TIAutocorrectionList * autocorrectionList;                        //@synthesize autocorrectionList=_autocorrectionList - In the implementation block
@property (nonatomic,readonly) NSArray * displayedCandidates; 
@property (assign,nonatomic) BOOL drawsBackdropView;                                           //@synthesize drawsBackdropView=_drawsBackdropView - In the implementation block
@property (assign,nonatomic) unsigned long long minimumNumberOfCells;                          //@synthesize minimumNumberOfCells=_minimumNumberOfCells - In the implementation block
@property (assign,nonatomic) unsigned long long maximumEmojiCells;                             //@synthesize maximumEmojiCells=_maximumEmojiCells - In the implementation block
@property (nonatomic,retain) NSLocale * currentLocale;                                         //@synthesize currentLocale=_currentLocale - In the implementation block
@property (assign,nonatomic) BOOL disablesHighlight;                                           //@synthesize disablesHighlight=_disablesHighlight - In the implementation block
@property (nonatomic,retain) UIKBRenderConfig * renderConfig;                                  //@synthesize renderConfig=_renderConfig - In the implementation block
@property (nonatomic,retain) UIColor * separatorColor;                                         //@synthesize separatorColor=_separatorColor - In the implementation block
@property (assign,nonatomic) double separatorMargin;                                           //@synthesize separatorMargin=_separatorMargin - In the implementation block
@property (nonatomic,retain) UIColor * highlightColor;                                         //@synthesize highlightColor=_highlightColor - In the implementation block
@property (assign,nonatomic) double highlightMargin;                                           //@synthesize highlightMargin=_highlightMargin - In the implementation block
@property (assign,nonatomic) double highlightCornerRadius;                                     //@synthesize highlightCornerRadius=_highlightCornerRadius - In the implementation block
@property (assign,nonatomic) BOOL useContinuousCornerInHighlight;                              //@synthesize useContinuousCornerInHighlight=_useContinuousCornerInHighlight - In the implementation block
@property (assign,nonatomic) BOOL shouldAnimateCells;                                          //@synthesize shouldAnimateCells=_shouldAnimateCells - In the implementation block 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)layoutSubviews;
-(void)setSeparatorColor:(UIColor *)arg1 ;
-(void)_setRenderConfig:(id)arg1 ;
-(NSLocale *)currentLocale;
-(UIColor *)separatorColor;
-(void)setAutocorrectionList:(TIAutocorrectionList *)arg1 ;
-(BOOL)_shouldPadWithEmptyCellsForAutocorrectionList:(id)arg1 ;
-(BOOL)drawsBackdropView;
-(BOOL)_ensureVisibleCellCount:(unsigned long long)arg1 forCellStackView:(id)arg2 ;
-(unsigned long long)minimumNumberOfCells;
-(NSArray *)displayedCandidates;
-(void)setTapGestureRecognizer:(UILongPressGestureRecognizer *)arg1 ;
-(UILongPressGestureRecognizer *)tapGestureRecognizer;
-(id)labelFontForCandidate:(id)arg1 ;
-(void)configurePredictionCell:(id)arg1 forCandidate:(id)arg2 animated:(BOOL)arg3 ;
-(void)setHighlightMargin:(double)arg1 ;
-(double)highlightMargin;
-(void)setAutocorrectionList:(id)arg1 animated:(BOOL)arg2 ;
-(void)setDelegate:(id<TUIPredictionViewDelegate>)arg1 ;
-(UIColor *)highlightColor;
-(void)_updateVisibleCellAppearance;
-(void)setSeparatorMargin:(double)arg1 ;
-(void)_reloadCellsAnimated:(BOOL)arg1 ;
-(void)setRenderConfig:(UIKBRenderConfig *)arg1 ;
-(long long)selectedIndex;
-(id)allVisibleCells;
-(void)setHighlightCornerRadius:(double)arg1 ;
-(id)_candidatesToDisplayForAutocorrectionList:(id)arg1 ;
-(BOOL)shouldAnimateCells;
-(void)setHighlightColor:(UIColor *)arg1 ;
-(void)setUseContinuousCornerInHighlight:(BOOL)arg1 ;
-(double)maximumBackgroundWidth;
-(void)setCurrentLocale:(NSLocale *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(UIKBRenderConfig *)renderConfig;
-(void)setDrawsBackdropView:(BOOL)arg1 ;
-(id<TUIPredictionViewDelegate>)delegate;
-(double)highlightCornerRadius;
-(long long)layoutDirection;
-(void)setMinimumNumberOfCells:(unsigned long long)arg1 ;
-(TIAutocorrectionList *)autocorrectionList;
-(void)setCellStackView:(TUIPredictionViewStackView *)arg1 ;
-(void)setMaximumEmojiCells:(unsigned long long)arg1 ;
-(id)visibleCells;
-(BOOL)disablesHighlight;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(long long)_numberOfEmojisToDisplayForAutocorrectionList:(id)arg1 withCandidatesShown:(id)arg2 ;
-(UIView *)backdropView;
-(void)setBackdropView:(UIView *)arg1 ;
-(unsigned long long)maximumEmojiCells;
-(void)_updateHighlightedCellForTouch:(id)arg1 ;
-(BOOL)useContinuousCornerInHighlight;
-(void)setSelectedIndex:(long long)arg1 ;
-(void)cancelTapGestureRecognizer;
-(CGSize)intrinsicContentSize;
-(void)_didRecognizeTapGesture:(id)arg1 ;
-(unsigned long long)_predictionCellIndexAtLocation:(CGPoint)arg1 ;
-(TUIPredictionViewStackView *)cellStackView;
-(double)separatorMargin;
-(id)test_cellForCandidate:(id)arg1 ;
-(void)setDisablesHighlight:(BOOL)arg1 ;
-(void)setShouldAnimateCells:(BOOL)arg1 ;
@end

