/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:30 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TextInputUI/TUICandidateBaseCell.h>

@class TIKeyboardCandidate, UILabel, UIImageView, UILayoutGuide, NSLayoutConstraint;

@interface TUISuggestionCandidateCell : TUICandidateBaseCell {

	TIKeyboardCandidate* _candidate;
	UILabel* _textLabel;
	UIImageView* _iconImageView;
	UILayoutGuide* _paddedContainer;
	UILayoutGuide* _centeredContainer;
	NSLayoutConstraint* _paddingBetweenConstraint;
	NSLayoutConstraint* _topPaddingConstraint;
	NSLayoutConstraint* _leftPaddingConstraint;
	NSLayoutConstraint* _bottomPaddingConstraint;
	NSLayoutConstraint* _rightPaddingConstraint;

}

@property (nonatomic,retain) UILabel * textLabel;                                        //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic,retain) UIImageView * iconImageView;                                //@synthesize iconImageView=_iconImageView - In the implementation block
@property (nonatomic,retain) UILayoutGuide * paddedContainer;                            //@synthesize paddedContainer=_paddedContainer - In the implementation block
@property (nonatomic,retain) UILayoutGuide * centeredContainer;                          //@synthesize centeredContainer=_centeredContainer - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * paddingBetweenConstraint;              //@synthesize paddingBetweenConstraint=_paddingBetweenConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * topPaddingConstraint;                  //@synthesize topPaddingConstraint=_topPaddingConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * leftPaddingConstraint;                 //@synthesize leftPaddingConstraint=_leftPaddingConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * bottomPaddingConstraint;               //@synthesize bottomPaddingConstraint=_bottomPaddingConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * rightPaddingConstraint;                //@synthesize rightPaddingConstraint=_rightPaddingConstraint - In the implementation block
@property (nonatomic,retain) TIKeyboardCandidate * candidate;                            //@synthesize candidate=_candidate - In the implementation block
+(id)reuseIdentifier;
-(void)layoutSubviews;
-(TIKeyboardCandidate *)candidate;
-(void)updateLabel;
-(id)bodyText;
-(void)didMoveToWindow;
-(id)image;
-(id)headerText;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setStyle:(id)arg1 ;
-(UIImageView *)iconImageView;
-(void)commonInit;
-(void)setCandidate:(TIKeyboardCandidate *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(UILabel *)textLabel;
-(NSLayoutConstraint *)topPaddingConstraint;
-(void)setTopPaddingConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setTextLabel:(UILabel *)arg1 ;
-(void)setIconImageView:(UIImageView *)arg1 ;
-(id)textSuggestion;
-(UILayoutGuide *)paddedContainer;
-(void)setPaddedContainer:(UILayoutGuide *)arg1 ;
-(UILayoutGuide *)centeredContainer;
-(void)setCenteredContainer:(UILayoutGuide *)arg1 ;
-(NSLayoutConstraint *)paddingBetweenConstraint;
-(void)setPaddingBetweenConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)leftPaddingConstraint;
-(void)setLeftPaddingConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)bottomPaddingConstraint;
-(void)setBottomPaddingConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)rightPaddingConstraint;
-(void)setRightPaddingConstraint:(NSLayoutConstraint *)arg1 ;
@end

