/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:29 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TextInput/TIKeyboardCandidateSingle.h>

@class NSString;

@interface TUITypedStringCandidate : TIKeyboardCandidateSingle {

	NSString* _displayLabel;

}

@property (nonatomic,retain) NSString * displayLabel;              //@synthesize displayLabel=_displayLabel - In the implementation block
+(id)typedStringCandidateWithLocale:(id)arg1 typedString:(id)arg2 rawTypedString:(id)arg3 ;
-(void)setDisplayLabel:(NSString *)arg1 ;
-(id)label;
-(NSString *)displayLabel;
@end

