/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:20 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation.h>

@class TIKeyboardCandidate, NSArray;

@interface TIAutocorrectionList : NSObject <NSSecureCoding> {

    BOOL _containsProactiveTriggers;
    BOOL _proactiveSuggestionsEmpty;
    TIKeyboardCandidate* _autocorrection;
    NSArray* _predictions;
    NSArray* _emojiList;
    NSArray* _proactiveTriggers;
}
@property (nonatomic,readonly) BOOL containsAutofillCandidates;
@property (nonatomic,readonly) BOOL containsContinuousPathConversions;
@property (nonatomic,readonly) BOOL notEmpty;
@property (nonatomic,readonly) BOOL isShowingSuggestionForKeyboardCamera;
@property (assign,nonatomic) BOOL containsProactiveTriggers;                                    //@synthesize containsProactiveTriggers=_containsProactiveTriggers - In the implementation block
@property (assign,nonatomic) BOOL proactiveSuggestionsEmpty;                                    //@synthesize proactiveSuggestionsEmpty=_proactiveSuggestionsEmpty - In the implementation block
@property (nonatomic,readonly) BOOL empty;
@property (nonatomic,readonly) TIKeyboardCandidate * autocorrection;                            //@synthesize autocorrection=_autocorrection - In the implementation block
@property (nonatomic,readonly) id predictions;                                           //@synthesize predictions=_predictions - In the implementation block
@property (nonatomic,readonly) id emojiList;                                             //@synthesize emojiList=_emojiList - In the implementation block
@property (nonatomic,readonly) id proactiveTriggers;                                     //@synthesize proactiveTriggers=_proactiveTriggers - In the implementation block
@property (nonatomic,readonly) BOOL hasSupplementalCandidates;
@property (nonatomic,readonly) TIKeyboardCandidate * autocorrectionIfSupplemental;
@property (nonatomic,readonly) id predictionsIfSupplemental;
@property (nonatomic,readonly) id candidates;
@property (nonatomic,readonly) BOOL shouldAcceptTopCandidate;
+(BOOL)supportsSecureCoding;
+(id)listWithPredictions:(id)arg1 emojiList:(id)arg2 proactiveTriggers:(id)arg3 ;
+(id)listWithAutocorrection:(id)arg1 predictions:(id)arg2 emojiList:(id)arg3 ;
+(id)listWithAutocorrection:(id)arg1 predictions:(id)arg2 ;
+(id)listWithAutocorrection:(id)arg1 ;
+(id)listWithAutocorrection:(id)arg1 predictions:(id)arg2 emojiList:(id)arg3 proactiveTriggers:(id)arg4 ;
+(id)listWithPredictions:(id)arg1 proactiveTriggers:(id)arg2 ;
+(id)autocorrectionListWithCandidates:(id)arg1 shouldAcceptTopCandidate:(BOOL)arg2 ;
-(id)ui_allSupplementalCandidates;
-(BOOL)containsAutofillCandidates;
-(BOOL)containsContinuousPathConversions;
-(BOOL)notEmpty;
-(void)updateLabelsWithSmartPunctuation:(id)arg1 ;
-(long long)sourceForAutocorrection;
-(BOOL)isShowingSuggestionForKeyboardCamera;
-(id)candidates;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)empty;
-(NSString *)description;
-(id)predictions;
-(id)initWithCoder:(id)arg1 ;
-(id)autocorrection;
-(id)proactiveTriggers;
-(BOOL)shouldAcceptTopCandidate;
-(id)emojiList;
-(BOOL)containsProactiveTriggers;
-(id)predictionsIfSupplemental;
-(id)autocorrectionIfSupplemental;
-(BOOL)proactiveSuggestionsEmpty;
-(instancetype)initWithAutocorrection:(id)arg1 predictions:(id)arg2 emojiList:(id)arg3 proactiveTriggers:(id)arg4 ;
-(id)initWithAutocorrectionAlternativeProactiveTrigger:(id)arg1 predictions:(id)arg2 emojiList:(id)arg3 proactiveTriggers:(id)arg4 ;
-(id)initWithCandidates:(id)arg1 ;
-(id)initWithCandidates:(id)arg1 shouldAcceptTopCandidate:(BOOL)arg2 ;
-(BOOL)hasSupplementalItems;
-(BOOL)hasSupplementalCandidates;
-(BOOL)isSupplementalCandidateInPredictions:(id)arg1 ;
-(void)setContainsProactiveTriggers:(BOOL)arg1 ;
-(void)setProactiveSuggestionsEmpty:(BOOL)arg1 ;
@end

//default    08:19:39.716521-0600    Antoine    arg1 Value: <TIZephyrCandidate: 0x283f2e760 'tesf' -> 'test' (extension: 0) UTM=All|Adapt|Near, SM=Static|Dynamic>

