/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:28 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TextInput/TIKeyboardCandidate.h>

@class NSString;

@interface TIKeyboardCandidateSingle : TIKeyboardCandidate {

	BOOL _extensionCandidate;
	NSString* _candidate;
	NSString* _input;
	NSString* _rawInput;
	NSString* _applicationKey;
	NSString* _applicationBundleId;
	NSString* _altDSID;
	long long _cursorMovement;
	NSString* _lexiconLocale;

}

@property (nonatomic) NSString * candidate;                                               //@synthesize candidate=_candidate - In the implementation block
@property (nonatomic) NSString * input;                                                   //@synthesize input=_input - In the implementation block
@property (nonatomic) NSString * rawInput;                                                //@synthesize rawInput=_rawInput - In the implementation block
@property (assign,nonatomic) long long cursorMovement;                                         //@synthesize cursorMovement=_cursorMovement - In the implementation block
@property (nonatomic) NSString * applicationKey;                                          //@synthesize applicationKey=_applicationKey - In the implementation block
@property (nonatomic) NSString * applicationBundleId;                                     //@synthesize applicationBundleId=_applicationBundleId - In the implementation block
@property (nonatomic) NSString * altDSID;                                                 //@synthesize altDSID=_altDSID - In the implementation block
@property (assign,getter=isExtensionCandidate,nonatomic) BOOL extensionCandidate;              //@synthesize extensionCandidate=_extensionCandidate - In the implementation block
@property (nonatomic,copy) NSString * lexiconLocale;                                           //@synthesize lexiconLocale=_lexiconLocale - In the implementation block
+(BOOL)supportsSecureCoding;
+(int)type;
+(id)candidateWithUnchangedInput:(id)arg1 ;
+(id)candidateWithCandidate:(id)arg1 forInput:(id)arg2 ;
+(id)candidateWithCandidate:(id)arg1 forInput:(id)arg2 extensionCandidate:(BOOL)arg3 ;
+(id)candidateWithCandidate:(id)arg1 forInput:(id)arg2 customInfoType:(unsigned long long)arg3 ;
+(id)candidateWithCandidate:(id)arg1 forInput:(id)arg2 cursorMovement:(long long)arg3 ;
+(id)secureCandidateForInput:(id)arg1 slotID:(unsigned)arg2 ;
+(id)secureCandidateForInput:(id)arg1 slotID:(unsigned)arg2 customInfoType:(unsigned long long)arg3 ;
+(id)secureCandidateForInput:(id)arg1 slotID:(unsigned)arg2 customInfoType:(unsigned long long)arg3 applicationKey:(id)arg4 applicationBundleId:(id)arg5 altDSID:(id)arg6 ;
-(NSString *)candidate;
-(NSString *)input;
-(NSString *)altDSID;
-(void)setAltDSID:(NSString *)arg1 ;
-(void)setInput:(NSString *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setCandidate:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)candidateByReplacingWithCandidate:(id)arg1 input:(id)arg2 ;
-(id)candidateByReplacingWithCandidate:(id)arg1 ;
-(long long)cursorMovement;
-(BOOL)isExtensionCandidate;
-(BOOL)isAutocorrectionIgnoringCaseAndDiacriticsAndSupplementalItemPrefix;
-(BOOL)isAutocorrectionIgnoringCaseAndSupplementalItemPrefix;
-(BOOL)isHideMyEmailType;
-(NSString *)rawInput;
-(id)initWithCandidateResultSetCoder:(id)arg1 ;
-(void)encodeWithCandidateResultSetCoder:(id)arg1 ;
-(NSString *)applicationKey;
-(NSString *)applicationBundleId;
-(id)candidateByReplacingWithCandidate:(id)arg1 input:(id)arg2 rawInput:(id)arg3 ;
-(id)initWithCandidate:(id)arg1 ;
-(id)initWithCandidate:(id)arg1 forInput:(id)arg2 ;
-(id)initWithCandidate:(id)arg1 forInput:(id)arg2 rawInput:(id)arg3 ;
-(id)initWithCandidate:(id)arg1 forInput:(id)arg2 rawInput:(id)arg3 extensionCandidate:(BOOL)arg4 ;
-(id)initWithUnchangedInput:(id)arg1 ;
-(id)initWithResponseCandidate:(id)arg1 ;
-(void)setRawInput:(NSString *)arg1 ;
-(void)setApplicationKey:(NSString *)arg1 ;
-(void)setApplicationBundleId:(NSString *)arg1 ;
-(void)setExtensionCandidate:(BOOL)arg1 ;
-(void)setCursorMovement:(long long)arg1 ;
-(NSString *)lexiconLocale;
-(void)setLexiconLocale:(NSString *)arg1 ;
@end

