/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:49:04 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/TextInputCore.framework/TextInputCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TextInput/TIKeyboardInputManagerStub.h>

@protocol TIKeyboardInputManagerLogging, TIClientProxy;
@class TIKeyboardInputManagerBase, NSString;

@interface TIKeyboardInputManagerWrapper : TIKeyboardInputManagerStub {

	TIKeyboardInputManagerBase* _inputManager;
	id<TIKeyboardInputManagerLogging> _logger;
	id<TIClientProxy> _clientProxy;
	NSString* _cachedContextChangeTrigger;

}

@property (nonatomic,retain) TIKeyboardInputManagerBase * inputManager;              //@synthesize inputManager=_inputManager - In the implementation block
@property (nonatomic,retain) id<TIKeyboardInputManagerLogging> logger;               //@synthesize logger=_logger - In the implementation block
@property (nonatomic,retain) id<TIClientProxy> clientProxy;                          //@synthesize clientProxy=_clientProxy - In the implementation block
@property (nonatomic,retain) NSString * cachedContextChangeTrigger;                  //@synthesize cachedContextChangeTrigger=_cachedContextChangeTrigger - In the implementation block
-(void)textAccepted:(id)arg1 ;
-(void)acceptingCandidateWithTrigger:(id)arg1 ;
-(id<TIKeyboardInputManagerLogging>)logger;
-(TIKeyboardInputManagerBase *)inputManager;
-(void)changingContextWithTrigger:(id)arg1 ;
-(void)setLogger:(id<TIKeyboardInputManagerLogging>)arg1 ;
-(id)init;
-(void)handleKeyboardState:(id)arg1 ;
-(void)setInputManager:(TIKeyboardInputManagerBase *)arg1 ;
-(void)handleKeyboardInput:(id)arg1 keyboardState:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)stickerWithIdentifier:(id)arg1 stickerRoles:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)syncToKeyboardState:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)skipHitTestForTouchEvent:(id)arg1 keyboardState:(id)arg2 ;
-(void)generateAutocorrectionsWithKeyboardState:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)generateAutocorrectionsWithKeyboardState:(id)arg1 candidateRange:(NSRange)arg2 requestToken:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)textAccepted:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)adjustPhraseBoundaryInForwardDirection:(BOOL)arg1 granularity:(int)arg2 keyboardState:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)candidateRejected:(id)arg1 ;
-(void)generateCandidatesWithKeyboardState:(id)arg1 candidateRange:(NSRange)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)generateCandidatesWithKeyboardState:(id)arg1 candidateRange:(NSRange)arg2 requestToken:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)generateReplacementsForString:(id)arg1 keyLayout:(id)arg2 continuation:(/*^block*/id)arg3 ;
-(void)handleAcceptedCandidate:(id)arg1 keyboardState:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)lastAcceptedCandidateCorrected;
-(void)logDiscoverabilityEvent:(int)arg1 userInfo:(id)arg2 ;
-(void)registerLearning:(id)arg1 fullCandidate:(id)arg2 keyboardState:(id)arg3 mode:(id)arg4 ;
-(void)setOriginalInput:(id)arg1 ;
-(void)skipHitTestForTouchEvents:(id)arg1 keyboardState:(id)arg2 ;
-(void)smartSelectionForTextInDocument:(id)arg1 inRange:(NSRange)arg2 language:(id)arg3 tokenizedRanges:(id)arg4 options:(unsigned long long)arg5 completion:(/*^block*/id)arg6 ;
-(void)writeTypologyLogWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)addSupplementalLexicon:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)adjustPhraseBoundaryInForwardDirection:(BOOL)arg1 keyboardState:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)generateAutocorrectionsWithKeyboardState:(id)arg1 candidateRange:(NSRange)arg2 completionHandler:(/*^block*/id)arg3 ;
-(id)generateInlineCompletions:(id)arg1 withPrefix:(id)arg2 ;
-(void)generateRefinementsForCandidate:(id)arg1 keyboardState:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)performHitTestForTouchEvent:(id)arg1 keyboardState:(id)arg2 continuation:(/*^block*/id)arg3 ;
-(void)performHitTestForTouchEvents:(id)arg1 keyboardState:(id)arg2 continuation:(/*^block*/id)arg3 ;
-(void)registerLearningForCompletion:(id)arg1 fullCompletion:(id)arg2 context:(id)arg3 prefix:(id)arg4 mode:(id)arg5 ;
-(void)removeSupplementalLexiconWithIdentifier:(unsigned long long)arg1 ;
-(id<TIClientProxy>)clientProxy;
-(void)_updateKeyboardOutput:(id)arg1 withSecureCandidatePayload:(id)arg2 keyboardState:(id)arg3 ;
-(void)setClientProxy:(id<TIClientProxy>)arg1 ;
-(void)acceptSecureCandidate:(id)arg1 keyboardState:(id)arg2 completion:(/*^block*/id)arg3 ;
-(NSString *)cachedContextChangeTrigger;
-(void)handleAcceptedCandidate:(id)arg1 acceptedSecureCandidate:(id)arg2 keyboardState:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)handleKeyboardInput:(id)arg1 acceptedSecureCandidate:(id)arg2 keyboardState:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)setCachedContextChangeTrigger:(NSString *)arg1 ;
-(void)updateAnalyticsForRejectedSuggestion:(id)arg1 keyboardState:(id)arg2 ;
@end

