/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:28 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TIKeyboardCandidateCoding <NSObject>
@required
+(int)type;
-(id)initWithCandidateResultSetCoder:(id)arg1;
-(void)encodeWithCandidateResultSetCoder:(id)arg1;

@end

