/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:27 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class NSString;

@interface TILexiconEntry : NSObject <NSCopying, NSSecureCoding> {

    NSString* _userInput;
    NSString* _documentText;
}
@property (nonatomic,readonly) NSString * documentText;              //@synthesize documentText=_documentText - In the implementation block
@property (nonatomic,readonly) NSString * userInput;                 //@synthesize userInput=_userInput - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)entryWithDocumentText:(id)arg1 userInput:(id)arg2 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(NSString *)documentText;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)userInput;
@end
