/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:36:27 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class NSArray;

@interface TILexicon : NSObject <NSCopying, NSSecureCoding> {

    NSArray* _entries;
}
@property (nonatomic,readonly) NSArray * entries;              //@synthesize entries=_entries - In the implementation block
+(BOOL)supportsSecureCoding;
+(void)requestLexiconFromBundlePath:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
+(id)lexiconWithEntries:(id)arg1 ;
-(NSArray *)entries;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
@end



